import{A as L,S as v,N as T,a as A}from"./assets/vendor-tBkKSLTP.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))n(s);new MutationObserver(s=>{for(const i of s)if(i.type==="childList")for(const r of i.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&n(r)}).observe(document,{childList:!0,subtree:!0});function o(s){const i={};return s.integrity&&(i.integrity=s.integrity),s.referrerPolicy&&(i.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?i.credentials="include":s.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function n(s){if(s.ep)return;s.ep=!0;const i=o(s);fetch(s.href,i)}})();document.addEventListener("DOMContentLoaded",function(){const e=document.querySelector(".open-menu-btn"),t=document.querySelector(".modal-close-btn"),o=document.querySelector(".modal-mob-menu"),n=document.querySelector(".modal-menu"),s=document.querySelector(".nav-header"),i=document.querySelector(".header-menu-button"),r=document.querySelector(".menu-list"),y=document.querySelector(".header-order-btn"),j=document.querySelector(".modal-order-button"),C=document.querySelectorAll(".modal-list-item");function w(){window.innerWidth<768?(e.classList.remove("visually-hidden"),s.classList.add("visually-hidden"),y.classList.add("visually-hidden")):(e.classList.add("visually-hidden"),o.classList.add("visually-hidden"),s.classList.remove("visually-hidden"),n.classList.add("visually-hidden"),r.classList.add("visually-hidden"),y.classList.remove("visually-hidden"))}e.addEventListener("click",function(){o.classList.remove("visually-hidden"),n.classList.remove("visually-hidden")}),t.addEventListener("click",function(){o.classList.add("visually-hidden"),n.classList.add("visually-hidden")});function b(){o.classList.add("visually-hidden"),n.classList.add("visually-hidden")}C.forEach(M=>{M.addEventListener("click",b)}),j.addEventListener("click",b),i.addEventListener("click",function(){r.classList.toggle("visually-hidden")}),window.addEventListener("resize",w),w()});const $=[{followLink:"https://www.instagram.com/goitclub/",text:"IG"},{followLink:"https://www.facebook.com/goITclub/",text:"FB"},{followLink:"https://www.youtube.com/c/GoIT",text:"YT"},{followLink:"https://github.com/RamiiaHolomoza/light-summer-project",text:"GH"},{followLink:"mailto:lloydjefferson@gmail.com",text:"lloydjefferson@gmail.com"}],P=document.querySelector(".hero-list");function H(e){return e.map(({followLink:t,text:o})=>`<li class="hero-list-item"><a
          href="${t}"
          class="hero-list-link"
          target="_blank"
          >${o}</a
        ></li>`).join("")}P.insertAdjacentHTML("beforeend",H($));const l="/footer-of-js-project/assets/icons-52vXHJ8M.svg";new L(".info-content-list",{duration:300,showMultiple:!0,openOnInit:[0]});const B=[{title:"ABOUT ME",content:'<p class="first-text">I am Lloyd Jefferson, a talented programmer with extensive expert in software development. I have an understanding of different programming languages ​​and technologies, always ready to improve my skills. I always follow the latest trends and look for unconventional, creative solutions to problems. I have a high level of analytical skills and am able to effectively solve even the most difficult tasks encountered on the way.</p><p  class="first-text">Able to work both independently and in a team. I can effectively cooperate with colleagues, exchanging ideas and finding optimal solutions. Professional maturity allows you to calmly cope with challenges and stressful situations, while maintaining a high quality of work. I am always looking for opportunities for self-improvement. I actively study new technologies and practices to stay abreast of the latest innovations. I have a strong understanding of various programming languages, frameworks and architectural concepts that allow me to create efficient and scalable software.</p>'},{title:"ROLE",content:`<p>'Frontend development"</p><p>"HeadlessCMS,Wordpress"</p><p>"Blender(enjoy)</p>`},{title:"EDUCATION",content:"<p>2018 - 2019 / Frontend Development Diploma, GoIT IT School, New York</p><p>2019 - 2020 / Advanced Web Development Certificate, GoIT IT School, New York</p><p>2020 - 2022 / Advanced Blender Animation Techniques, Udemy</p>"}],S=document.querySelector(".info-content-list");function R(e){return e.map(({title:t,content:o},n)=>`
        <li class="info-content-item ${n===0?"is-active":""}">
        <h3 class="accordion-header info-title-acc"><p>${t}</p><button type="button" class="acc-btn"><svg class="about-acc-icon" width="18" height="18">
            <use href="${l}#icon-Icon-${n===0?"top":"bottom"}"></use></button></h3>
        <div class="accordion-content info-text-acc">${o}</div>
        </li>
            `).join("")}S.insertAdjacentHTML("beforeend",R(B));S.addEventListener("click",O);const x=document.querySelector(".info-content-item.is-active .accordion-content");x.style.maxHeight=x.scrollHeight+"px";function O(e){const t=e.target.closest(".acc-btn"),o=t.querySelector(".about-acc-icon");if(t){const n=t.closest(".info-content-item"),s=n.querySelector(".accordion-content");n.classList.toggle("is-active"),n.classList.contains("is-active")?s.style.maxHeight=s.scrollHeight+"px":s.style.maxHeight=0}o.classList.toggle("rotate180")}const V=["HTML/CSS","JavaScript","React","Node.js","React Native"," Soft skills"],N=document.querySelector(".skills-content-list");V.forEach(e=>{const t=document.createElement("li");t.classList.add("swiper-slide","slide-item-ab"),t.innerHTML=`<p class="swiper-ab-text">${e}</p>`,N.appendChild(t)});const D=new v(".skilla-about-swiper",{slidesPerView:6,slidesPerGroup:1,spaceBetween:0,modules:[T],loop:!0,navigation:{nextEl:".swiper-button-next-ab"},breakpoints:{320:{slidesPerView:"auto"},768:{slidesPerView:"auto"},1440:{slidesPerView:"auto"}}});D.update();document.querySelector(".swiper-button-next-ab").addEventListener("click",()=>{if(1399<window.innerWidth){const t=document.querySelector(".swiper-slide-active");let o=t.nextElementSibling;o||(o=document.querySelector(".swiper-slide:first-child")),t.classList.remove("swiper-slide-active"),o.classList.add("swiper-slide-active")}});const W=[{svgroot:`${l}#icon-user-01`,topic:"Expertise",text:"As a highly experienced developer, I have deep knowledge of programming and website development."},{svgroot:`${l}#icon-message-chat-circle`,topic:"Communication",text:"Understanding your needs and wants is my priority and I am always open to discussions and corrections."},{svgroot:`${l}#icon-brush-01`,topic:"Art",text:"Thanks to my creative nature, I am ready to accept challenges and help you bring your ideas to life. "},{svgroot:`${l}#icon-hourglass-02`,topic:"Urgent execution",text:"I understand how important time is to you. Ready to work quickly and efficiently, without reducing the quality of work."}],k=document.querySelector(".benefits-list");function F(e){return e.map(({svgroot:t,topic:o,text:n})=>`<li class="benefits-list-item">
          <svg class="benefits-icon" width="24" height="24">
            <use href="${t}"></use>
          </svg>
          <div>
            <h5 class="benefits-topic">${o}</h5>
            <p class="benefits-text">${n}</p>
          </div>
        </li>`).join("")}k.insertAdjacentHTML("beforeend",F(W));function z(e){const t=e.target.closest(".benefits-list-item");if(t){const o=t.querySelector(".benefits-topic").textContent;alert(`You clicked on: ${o}`)}}k.addEventListener("click",z);new v(".swiper",{direction:"horizontal",pagination:{el:".swiper-pagination"},navigation:{nextEl:".custom-button-next",prevEl:".custom-button-prev"}});new L(".faq-container",{duration:400,ariaEnabled:!0,showMultiple:!1,collapse:!0});const G=[{svgroot:"#icon-Icon-bottom",topic:"What programming languages ​​are most often used in your project?",text:"In the field of web development, there are various technologies and programming languages. Typically, this includes a combination of frontend (client side) and backend (server side) languages."},{svgroot:"#icon-Icon-bottom",topic:"What are the deadlines for the project?",text:"The terms of project implementation depend to a large extent on a number of factors, such as the scope of the project, its complexity, and the availability of resources. Determining exact deadlines is a difficult task, and it usually occurs during the planning phase of the project."},{svgroot:"#icon-Icon-bottom",topic:"What payment methods do you accept?",text:"Payment through credit and debit cards such as Visa, MasterCard, specialized electronic payment systems such as PayPal, as well as payments in cryptocurrencies such as Bitcoin, Ethereum and others."},{svgroot:"#icon-Icon-bottom",topic:"How can I contact you?",text:"In the field of web development, there are various technologies and programming languages. Typically, this includes a combination of frontend (client side) and backend (server side) languages."},{svgroot:"#icon-Icon-bottom",topic:"Do you provide advice or support?",text:"The terms of project implementation depend to a large extent on a number of factors, such as the scope of the project, its complexity, and the availability of resources. Determining exact deadlines is a difficult task, and it usually occurs during the planning phase of the project."},{svgroot:"#icon-Icon-bottom",topic:"What does the process of developing a software<br >product look like from idea to implementation?",text:"Payment through credit and debit cards such as Visa, MasterCard, specialized electronic payment systems such as PayPal, as well as payments in cryptocurrencies such as Bitcoin, Ethereum and others."}],E=document.querySelector(".faq-container");function U(e){return e.map(({svgroot:t,topic:o,text:n},s)=>`
          <li class="faq ${s!==e.length-1,""}">
            <div class="faq-list-up">
               <h3 class="question">${o}</h3>
                 <p class="faq-icon">
                 <svg width="20" height="20">
                   <use href="${l}${t}" ></use>
                </svg>
                </p>
           </div>
          <p class="faq-text">${n}</p>
          </li>`).join("")}E.insertAdjacentHTML("beforeend",U(G));function J(e){if(e.target.closest(".faq-icon")){const t=e.target.closest(".faq"),o=t.querySelector(".faq-text"),n=t.querySelector(".faq-icon");t.classList.toggle("active"),n.classList.toggle("rotate"),t.classList.contains("active")?o.style.maxHeight=o.scrollHeight+"px":o.style.maxHeight=0}}E.addEventListener("click",J);const Y=document.createElement("style");document.head.appendChild(Y);const _=[{imagen1x:"./img/covers/project1.png",imagen2x:"./img/covers/project1-retina.png"},{imagen1x:"./img/covers/project2.png",imagen2x:"./img/covers/project2-retina.png"},{imagen1x:"./img/covers/project3.png",imagen2x:"./img/covers/project3-retina.png"},{imagen1x:"./img/covers/project4.png",imagen2x:"./img/covers/project4-retina.png"},{imagen1x:"./img/covers/project5.png",imagen2x:"./img/covers/project5-retina.png"},{imagen1x:"./img/covers/project6.png",imagen2x:"./img/covers/project6-retina.png"},{imagen1x:"./img/covers/project7.png",imagen2x:"./img/covers/project7-retina.png"},{imagen1x:"./img/covers/project8.png",imagen2x:"./img/covers/project8-retina.png"},{imagen1x:"./img/covers/project9.png",imagen2x:"./img/covers/project9-retina.png"},{imagen1x:"./img/covers/project10.png",imagen2x:"./img/covers/project10-retina.png"}];function K(e,t){const o=[];for(;o.length<t;)o.push(...e);return o.slice(0,t)}const Z=K(_,25);function Q(e){return e.map(({imagen1x:t,imagen2x:o})=>`
<li class="covers-project">
  <picture>
    <source
      srcset="${t} 1x, ${o} 2x"
      media="(min-width: 320px)"
    />

    <img class="covers-img" src="${t}" alt="Covers" />
  </picture>
</li>
`).join("")}const X=document.querySelectorAll(".covers-list");X.forEach((e,t)=>{const o=t*3,n=o+5;e.innerHTML=Q(Z.slice(o,n))});const ee=document.querySelector(".covers-content"),p=document.querySelectorAll(".covers-project"),te=document.querySelector(".container-reviews");function oe(){for(let e=0;e<p.length;e++){const t=window.innerHeight,n=ee.getBoundingClientRect().top,i=te.getBoundingClientRect().top;n<t*.9?p[e].classList.add("covers-animation"):p[e].classList.remove("covers-animation"),i<t*.2&&p[e].classList.remove("covers-animation")}}window.addEventListener("scroll",oe);let g=0,a=0;async function h(e=0,t=4){try{const n=(await A.get("https://portfolio-js.b.goit.study/api/reviews")).data;if(g=n.length,g===0)se("Not found");else{const s=n.slice(e,e+t);ne(s),q(t)}}catch{const n=document.querySelector(".section-reviews");new IntersectionObserver(i=>{i.forEach(r=>{r.isIntersecting&&ie("Failed to load reviews. Please try again.")})}).observe(n)}}function ne(e){const t=document.querySelector(".swiper-wrapper.swiper-rew");t.innerHTML="",e.forEach(o=>{const n=document.createElement("li");n.classList.add("swiper-slide","review-item"),n.innerHTML=`
      <div class="review-item-content">
        <img class="image-reviews" src="${o.avatar_url}" alt="${o.author}">
        <b class="name-reviews">${o.author}</b>
        <p class="text-reviews">${o.review}</p>
      </div>`,t.appendChild(n)}),u.update()}function se(e){const t=document.querySelector(".swiper-wrapper.swiper-rew"),o=document.createElement("li");o.classList.add("swiper-slide","review-item"),o.textContent=e,t.appendChild(o)}function ie(e){const t=document.querySelector(".error-popup");t.textContent=e,t.classList.add("active"),setTimeout(()=>{t.classList.remove("active")},3e3)}function q(e){const t=document.querySelector(".swiper-button-prev"),o=document.querySelector(".swiper-button-next");a===0?t.classList.add("swiper-button-disabled"):t.classList.remove("swiper-button-disabled"),a+e>=g?o.classList.add("swiper-button-disabled"):o.classList.remove("swiper-button-disabled")}const u=new v(".reviews-slider",{slidesPerView:4,spaceBetween:16,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},keyboard:{enabled:!0,onlyInViewport:!0},simulateTouch:!0,touchRatio:1,touchAngle:45,grabCursor:!0,longSwipesMs:300,longSwipesRatio:.5,threshold:10,resistance:!0,resistanceRatio:.85,breakpoints:{320:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:4}},on:{slideChange:()=>q(u.params.slidesPerView)}});document.querySelector(".swiper-button-next").addEventListener("click",()=>{const e=u.params.slidesPerView;a+e<g&&(a+=1,h(a,e))});document.querySelector(".swiper-button-prev").addEventListener("click",()=>{const e=u.params.slidesPerView;a>0&&(a-=1,h(a,e))});const ae=u.params.slidesPerView;h(a,ae);const m=document.querySelector(".footer-form"),d=document.getElementById("modal"),re=document.querySelector(".footer-close-button"),c=document.getElementById("email-message"),I="feedback-form-state";let f={email:"",comments:""};me();m.addEventListener("input",ce);m.addEventListener("submit",le);function ce(e){const{value:t,name:o}=e.target;f[o]=t.trim(),localStorage.setItem(I,JSON.stringify(f)),o==="email"&&de(e.target)}function le(e){e.preventDefault(),m.checkValidity()?ue():alert("Fill in all fields")}function de(e){/^\w+(\.\w+)?@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/.test(e.value.trim())?(c.textContent="Success!",c.classList.add("success"),c.classList.remove("error")):(c.textContent="Invalid email, try again",c.classList.add("error"),c.classList.remove("success"))}function ue(){m.reset(),c.textContent=" ",d.classList.add("is-open")}re.addEventListener("click",function(){d.classList.remove("is-open")});d.addEventListener("click",function(e){e.target===d&&d.classList.remove("is-open")});window.addEventListener("keydown",e=>{e.key==="Escape"&&d.classList.remove("is-open")});function me(){const e=JSON.parse(localStorage.getItem(I));if(e)for(const t in e)e.hasOwnProperty(t)&&(m.elements[t].value=e[t],f[t]=e[t])}
//# sourceMappingURL=commonHelpers.js.map
